version: '3.7'
services:
  eventer-base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: eventer-base:latest

  eventer-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - HASH_ID_SALT
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - GUARDIAN_SECRET_KEY
    image: disappearer/eventer
    ports:
      - 4000:4000
    environment:
      SECRET_KEY_BASE:
      DATABASE_URL: 'ecto://db_user:${POSTGRES_PASSWORD}@db/eventer'
      HASH_ID_SALT:
      GOOGLE_CLIENT_ID:
      GOOGLE_CLIENT_SECRET:
      GUARDIAN_SECRET_KEY:
    depends_on:
      - eventer-db-prod

  eventer-db-prod:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: eventer
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD:

  eventer-test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        - HASH_ID_SALT
    environment:
      DATABASE_URL: 'ecto://postgres:postgres@eventer-db-test/eventer_test'
      HASH_ID_SALT:
    depends_on:
      - eventer-db-test
    command: './run-tests'

  eventer-db-test:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: eventer_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
