################
# prepare test #
################

FROM eventer-base:latest AS test

ARG HASH_ID_SALT
ARG GOOGLE_APPLICATION_CREDENTIALS=/app/service_account.json

# build deps
ENV MIX_ENV=test

RUN mix do deps.get --only $MIX_ENV, deps.compile
RUN mix compile
